CREATE TABLE ISSUESLISTS
(
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(100)
);

CREATE TABLE ISSUES
(
    ID SERIAL PRIMARY KEY,
    ISSUESLIST_ID BIGINT UNSIGNED NOT NULL,
    FOREIGN KEY (ISSUESLIST_ID) REFERENCES ISSUESLISTS(ID),
    SUMMARY VARCHAR(200),
    DESCRIPTION VARCHAR(2000),
    USER_ID_ASSIGNEDTO BIGINT UNSIGNED NOT NULL,
    FOREIGN KEY (USER_ID_ASSIGNEDTO) REFERENCES USERS(ID)

);

SELECT * FROM ISSUESLISTS;
SELECT * FROM ISSUES;

INSERT INTO ISSUESLISTS (NAME)
VALUES ("ToDo");
INSERT INTO ISSUESLISTS (NAME)
VALUES ("InProgress");
INSERT INTO ISSUESLISTS (NAME)
VALUES ("Done");
COMMIT;

INSERT INTO ISSUES (ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO)
VALUES (1, "Task 1", "High priority", 1);
INSERT INTO ISSUES (ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO)
VALUES (1, "Task 2", "High priority", 2);
INSERT INTO ISSUES (ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO)
VALUES (1, "Task 3", "Low priority", 3);
INSERT INTO ISSUES (ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO)
VALUES (1, "Task 4", "Low priority", 4);
INSERT INTO ISSUES (ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO)
VALUES (1, "Task 5", "High priority", 5);
COMMIT;

INSERT INTO ISSUES (ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO)
VALUES (2, "Task 1", "High priority", 5);
INSERT INTO ISSUES (ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO)
VALUES (2, "Task 2", "High priority", 4);
INSERT INTO ISSUES (ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO)
VALUES (2, "Task 3", "Low priority", 3);
INSERT INTO ISSUES (ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO)
VALUES (2, "Task 4", "Low priority", 2);
INSERT INTO ISSUES (ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO)
VALUES (2, "Task 5", "High priority", 1);
COMMIT;

INSERT INTO ISSUES (ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO)
VALUES (3, "Task 1", "High priority", 3);
INSERT INTO ISSUES (ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO)
VALUES (3, "Task 2", "High priority", 3);
INSERT INTO ISSUES (ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO)
VALUES (3, "Task 3", "Low priority", 1);
INSERT INTO ISSUES (ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO)
VALUES (3, "Task 4", "Low priority", 4);
INSERT INTO ISSUES (ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO)
VALUES (3, "Task 5", "High priority", 2);
COMMIT;


UPDATE ISSUES SET SUMMARY='Task 1.1' WHERE ID='1';
UPDATE ISSUES SET SUMMARY='Task 1.2' WHERE ID='2';
UPDATE ISSUES SET SUMMARY='Task 1.3' WHERE ID='3';
UPDATE ISSUES SET SUMMARY='Task 1.4' WHERE ID='4';
UPDATE ISSUES SET SUMMARY='Task 1.5' WHERE ID='5';
UPDATE ISSUES SET SUMMARY='Task 2.1' WHERE ID='6';
UPDATE ISSUES SET SUMMARY='Task 2.2' WHERE ID='7';
UPDATE ISSUES SET SUMMARY='Task 2.3' WHERE ID='8';
UPDATE ISSUES SET SUMMARY='Task 2.4' WHERE ID='9';
UPDATE ISSUES SET SUMMARY='Task 2.5' WHERE ID='10';
UPDATE ISSUES SET SUMMARY='Task 3.1' WHERE ID='11';
UPDATE ISSUES SET SUMMARY='Task 3.2' WHERE ID='12';
UPDATE ISSUES SET SUMMARY='Task 3.3' WHERE ID='13';
UPDATE ISSUES SET SUMMARY='Task 3.4' WHERE ID='14';
UPDATE ISSUES SET SUMMARY='Task 3.5' WHERE ID='15';
COMMIT;
